-- =============================================================
-- Database Schema Definitions — Interview Preparation Platform
-- Generated by: db_architect_agent | Date: 2026-05-26
-- Engine: PostgreSQL 16
-- Extensions: pgcrypto, pg_trgm, uuid-ossp
-- =============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- =============================================================
-- ENUMS
-- =============================================================

CREATE TYPE user_role AS ENUM ('candidate', 'expert', 'admin');
CREATE TYPE user_status AS ENUM ('pending_verification', 'active', 'suspended', 'deleted');
CREATE TYPE expert_status AS ENUM ('pending_review', 'approved', 'rejected');
CREATE TYPE career_level AS ENUM ('entry', 'mid', 'senior', 'executive');
CREATE TYPE interview_track AS ENUM ('general', 'software_engineering', 'medical_residency');
CREATE TYPE question_type AS ENUM ('behavioral', 'technical', 'situational', 'role_specific');
CREATE TYPE question_status AS ENUM ('draft', 'published', 'archived');
CREATE TYPE session_type AS ENUM ('ai_mock', 'live_human', 'self_practice');
CREATE TYPE session_status AS ENUM (
  'awaiting_consent', 'in_progress', 'processing', 'scored', 'failed', 'cancelled'
);
CREATE TYPE booking_status AS ENUM ('confirmed', 'cancelled', 'completed', 'no_show');
CREATE TYPE consent_type AS ENUM ('ai_session', 'live_session');
CREATE TYPE job_status AS ENUM ('queued', 'processing', 'completed', 'failed');

-- =============================================================
-- USERS
-- =============================================================

CREATE TABLE users (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email           BYTEA NOT NULL,           -- pgcrypto encrypted
  email_hash      TEXT UNIQUE NOT NULL,     -- SHA-256 hash for lookups
  full_name       BYTEA NOT NULL,           -- pgcrypto encrypted
  role            user_role NOT NULL DEFAULT 'candidate',
  status          user_status NOT NULL DEFAULT 'pending_verification',
  email_verified  BOOLEAN NOT NULL DEFAULT FALSE,
  google_id       TEXT UNIQUE,              -- NULL if email/password auth
  avatar_url      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at      TIMESTAMPTZ               -- soft delete; hard delete via cron after 30 days
);

CREATE INDEX idx_users_role ON users(role) WHERE deleted_at IS NULL;
CREATE INDEX idx_users_status ON users(status) WHERE deleted_at IS NULL;

-- =============================================================
-- CANDIDATE PROFILES
-- =============================================================

CREATE TABLE candidate_profiles (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id             UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  target_industry     TEXT,
  career_level        career_level,
  interview_track     interview_track NOT NULL DEFAULT 'general',
  -- Resume parsed fields (stored as plain text after extraction)
  current_role        TEXT,
  skills              TEXT[],
  years_experience    INTEGER,
  resume_s3_key       TEXT,               -- S3 object key for raw resume file
  resume_parsed_at    TIMESTAMPTZ,
  resume_confidence   NUMERIC(3,2),       -- 0.00 – 1.00
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================
-- EXPERT PROFILES
-- =============================================================

CREATE TABLE expert_profiles (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id             UUID NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  status              expert_status NOT NULL DEFAULT 'pending_review',
  bio                 TEXT,
  specialties         TEXT[],             -- e.g. ['software_engineering', 'product_management']
  years_experience    INTEGER,
  linkedin_url        TEXT,
  rejection_reason    TEXT,               -- set if status = 'rejected'
  reviewed_by         UUID REFERENCES users(id),
  reviewed_at         TIMESTAMPTZ,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_expert_status ON expert_profiles(status);

-- =============================================================
-- EXPERT AVAILABILITY
-- =============================================================

CREATE TABLE expert_availability (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  expert_id       UUID NOT NULL REFERENCES expert_profiles(id) ON DELETE CASCADE,
  slot_start      TIMESTAMPTZ NOT NULL,
  slot_end        TIMESTAMPTZ NOT NULL,
  is_booked       BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_slot_order CHECK (slot_end > slot_start)
);

CREATE INDEX idx_availability_expert ON expert_availability(expert_id, slot_start)
  WHERE is_booked = FALSE;

-- =============================================================
-- QUESTIONS
-- =============================================================

CREATE TABLE questions (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  type            question_type NOT NULL,
  industry        TEXT NOT NULL DEFAULT 'general',
  career_level    career_level,
  difficulty      SMALLINT NOT NULL CHECK (difficulty BETWEEN 1 AND 5),
  text            TEXT NOT NULL,
  framework       TEXT,                   -- e.g. 'STAR', 'SOAR'
  tags            TEXT[],
  status          question_status NOT NULL DEFAULT 'draft',
  created_by      UUID REFERENCES users(id),
  published_at    TIMESTAMPTZ,
  -- Full-text search vector (auto-maintained by trigger)
  search_vector   TSVECTOR,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- GIN index for full-text search
CREATE INDEX idx_questions_search ON questions USING GIN(search_vector);
-- GIN index for tags array
CREATE INDEX idx_questions_tags ON questions USING GIN(tags);
CREATE INDEX idx_questions_type_level ON questions(type, career_level, status);

-- Trigger to maintain search_vector
CREATE OR REPLACE FUNCTION questions_search_vector_update() RETURNS TRIGGER AS $$
BEGIN
  NEW.search_vector := to_tsvector('english',
    COALESCE(NEW.text, '') || ' ' ||
    COALESCE(array_to_string(NEW.tags, ' '), '') || ' ' ||
    COALESCE(NEW.industry, '')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER questions_search_vector_trigger
  BEFORE INSERT OR UPDATE ON questions
  FOR EACH ROW EXECUTE FUNCTION questions_search_vector_update();

-- =============================================================
-- QUESTION ANSWERS (Sample answers per question)
-- =============================================================

CREATE TABLE question_answers (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  question_id     UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  answer_text     TEXT NOT NULL,
  keywords        TEXT[],                 -- expected keywords for AI scoring
  created_by      UUID REFERENCES users(id),
  is_primary      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_answers_question ON question_answers(question_id);

-- =============================================================
-- CANDIDATE BOOKMARKS
-- =============================================================

CREATE TABLE candidate_bookmarks (
  candidate_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  question_id     UUID NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (candidate_id, question_id)
);

-- =============================================================
-- MOCK SESSIONS (AI and Self-Practice)
-- =============================================================

CREATE TABLE mock_sessions (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  candidate_id    UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type            session_type NOT NULL DEFAULT 'ai_mock',
  status          session_status NOT NULL DEFAULT 'awaiting_consent',
  track           interview_track NOT NULL DEFAULT 'general',
  career_level    career_level,
  question_count  SMALLINT NOT NULL DEFAULT 5,
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  -- Scoring summary (denormalized for dashboard queries)
  composite_score SMALLINT CHECK (composite_score BETWEEN 0 AND 100),
  avg_wpm         SMALLINT,
  total_fillers   SMALLINT,
  -- Storage
  recording_s3_key    TEXT,              -- main recording object key (may be composite)
  transcript_s3_key   TEXT,
  -- Retention
  retain_until    TIMESTAMPTZ,           -- NULL = default 90-day policy
  deleted_at      TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_mock_sessions_candidate ON mock_sessions(candidate_id, created_at DESC)
  WHERE deleted_at IS NULL;
CREATE INDEX idx_mock_sessions_status ON mock_sessions(status);

-- =============================================================
-- SESSION RESPONSES (per-question recordings)
-- =============================================================

CREATE TABLE session_responses (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id      UUID NOT NULL REFERENCES mock_sessions(id) ON DELETE CASCADE,
  question_id     UUID NOT NULL REFERENCES questions(id),
  response_index  SMALLINT NOT NULL,
  recording_s3_key    TEXT,
  transcript      TEXT,                  -- STT output for this response
  duration_seconds    INTEGER,
  -- Per-response AI scores
  speech_rate_wpm     SMALLINT,
  filler_word_count   SMALLINT,
  filler_percentage   NUMERIC(5,2),
  keyword_relevance   SMALLINT,
  clarity_score       SMALLINT,
  improvement_tip     TEXT,
  scored_at       TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_responses_session ON session_responses(session_id, response_index);

-- =============================================================
-- LIVE SESSIONS (Human-Led Bookings)
-- =============================================================

CREATE TABLE live_sessions (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  candidate_id    UUID NOT NULL REFERENCES users(id),
  expert_id       UUID NOT NULL REFERENCES expert_profiles(id),
  availability_id UUID NOT NULL REFERENCES expert_availability(id),
  status          booking_status NOT NULL DEFAULT 'confirmed',
  starts_at       TIMESTAMPTZ NOT NULL,
  duration_minutes SMALLINT NOT NULL DEFAULT 45,
  candidate_notes TEXT,
  cancelled_by    UUID REFERENCES users(id),
  cancelled_at    TIMESTAMPTZ,
  cancel_reason   TEXT,
  recording_s3_key    TEXT,
  -- Retention
  retain_until    TIMESTAMPTZ,
  deleted_at      TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_live_sessions_candidate ON live_sessions(candidate_id, starts_at DESC);
CREATE INDEX idx_live_sessions_expert ON live_sessions(expert_id, starts_at);
CREATE INDEX idx_live_sessions_status ON live_sessions(status, starts_at);

-- =============================================================
-- RUBRIC EVALUATIONS
-- =============================================================

CREATE TABLE rubric_evaluations (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  live_session_id UUID NOT NULL UNIQUE REFERENCES live_sessions(id) ON DELETE CASCADE,
  expert_id       UUID NOT NULL REFERENCES users(id),
  -- Scored 1–5
  score_communication SMALLINT CHECK (score_communication BETWEEN 1 AND 5),
  score_competence    SMALLINT CHECK (score_competence BETWEEN 1 AND 5),
  score_confidence    SMALLINT CHECK (score_confidence BETWEEN 1 AND 5),
  score_preparation   SMALLINT CHECK (score_preparation BETWEEN 1 AND 5),
  -- Comments
  comment_communication TEXT,
  comment_competence    TEXT,
  comment_confidence    TEXT,
  comment_preparation   TEXT,
  overall_summary   TEXT,
  -- Composite score (avg of 4 categories × 20)
  composite_score   SMALLINT GENERATED ALWAYS AS (
    ((score_communication + score_competence + score_confidence + score_preparation)::NUMERIC / 4 * 20)::SMALLINT
  ) STORED,
  submitted_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================
-- CONSENT LOG (INSERT ONLY — enforced by application role)
-- =============================================================

CREATE TABLE consent_log (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id         UUID NOT NULL REFERENCES users(id),
  session_id      UUID NOT NULL,          -- references mock_sessions or live_sessions
  consent_type    consent_type NOT NULL,
  accepted        BOOLEAN NOT NULL,
  accepted_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address      TEXT NOT NULL,
  user_agent      TEXT
);

CREATE INDEX idx_consent_session ON consent_log(session_id);
CREATE INDEX idx_consent_user ON consent_log(user_id);

-- IMPORTANT: Grant INSERT only to the application DB role
-- REVOKE UPDATE, DELETE ON consent_log FROM app_role;

-- =============================================================
-- AUDIT LOG (INSERT ONLY)
-- =============================================================

CREATE TABLE audit_log (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  actor_id        UUID REFERENCES users(id),
  action          TEXT NOT NULL,          -- e.g. 'user.suspend', 'question.publish'
  target_type     TEXT NOT NULL,          -- e.g. 'user', 'question'
  target_id       UUID,
  metadata        JSONB,                  -- action-specific context
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_actor ON audit_log(actor_id, created_at DESC);
CREATE INDEX idx_audit_target ON audit_log(target_type, target_id);

-- IMPORTANT: Grant INSERT only to the application DB role
-- REVOKE UPDATE, DELETE ON audit_log FROM app_role;

-- =============================================================
-- ASYNC JOB TRACKING (for monitoring & retry visibility)
-- =============================================================

CREATE TABLE async_jobs (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  job_type        TEXT NOT NULL,          -- 'stt_transcription', 'ai_scoring', 'email'
  status          job_status NOT NULL DEFAULT 'queued',
  reference_id    UUID,                   -- session_id or response_id
  attempts        SMALLINT NOT NULL DEFAULT 0,
  max_attempts    SMALLINT NOT NULL DEFAULT 3,
  error_message   TEXT,
  queued_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ
);

CREATE INDEX idx_jobs_status ON async_jobs(status, queued_at);
CREATE INDEX idx_jobs_reference ON async_jobs(reference_id, job_type);

-- =============================================================
-- UPDATED_AT TRIGGER (applied to all mutable tables)
-- =============================================================

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON candidate_profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON expert_profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER set_updated_at BEFORE UPDATE ON questions
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
