/**
 * E2E Tests — Full Candidate Journey
 * Generated by: qa_developer_agent | Date: 2026-05-26
 * Tool: Playwright
 *
 * Covers user stories: US-01, US-02, US-03, US-05, US-06, US-09, US-10, US-15
 *
 * Prerequisites:
 *   - Staging environment running with seed data (002_seed_questions.sql)
 *   - PLAYWRIGHT_BASE_URL env var set to staging URL
 *   - Test user pre-created via API fixture (see global-setup.ts)
 */

import { test, expect, Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? 'http://localhost:3000'

// ── Fixtures ──────────────────────────────────────────────────

const TEST_USER = {
  email: `e2e-candidate-${Date.now()}@platform-test.com`,
  password: 'E2eTestPass1!',
  fullName: 'E2E Test Candidate',
}

// ── Helpers ───────────────────────────────────────────────────

async function registerAndLogin(page: Page) {
  await page.goto(`${BASE_URL}/register`)
  await page.getByLabel('Full name').fill(TEST_USER.fullName)
  await page.getByLabel('Email').fill(TEST_USER.email)
  await page.getByLabel('Password').fill(TEST_USER.password)
  await page.getByRole('radio', { name: 'Candidate' }).check()
  await page.getByRole('button', { name: 'Create account' }).click()
  // In test env, email verification is auto-confirmed for @platform-test.com emails
  await expect(page.getByText('Check your email')).toBeVisible()
  await page.goto(`${BASE_URL}/login`)
  await page.getByLabel('Email').fill(TEST_USER.email)
  await page.getByLabel('Password').fill(TEST_USER.password)
  await page.getByRole('button', { name: 'Sign in' }).click()
  await expect(page).toHaveURL(/\/dashboard/)
}

// ── US-01: Candidate Registration ────────────────────────────

test.describe('US-01 — Candidate Registration', () => {
  test('registers with email and password, sees verification notice', async ({ page }) => {
    await page.goto(`${BASE_URL}/register`)

    await page.getByLabel('Full name').fill('New Candidate')
    await page.getByLabel('Email').fill(`new-${Date.now()}@platform-test.com`)
    await page.getByLabel('Password').fill('NewPass123!')
    await page.getByRole('radio', { name: 'Candidate' }).check()
    await page.getByRole('button', { name: 'Create account' }).click()

    await expect(page.getByText(/check your email/i)).toBeVisible()
  })

  test('shows error for duplicate email', async ({ page }) => {
    await page.goto(`${BASE_URL}/register`)
    await page.getByLabel('Full name').fill('Duplicate')
    await page.getByLabel('Email').fill('existing@platform-test.com') // pre-seeded in test env
    await page.getByLabel('Password').fill('Pass123!')
    await page.getByRole('radio', { name: 'Candidate' }).check()
    await page.getByRole('button', { name: 'Create account' }).click()

    await expect(page.getByText(/already registered/i)).toBeVisible()
  })

  test('registration page has no critical accessibility violations', async ({ page }) => {
    await page.goto(`${BASE_URL}/register`)
    const results = await new AxeBuilder({ page }).analyze()
    const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
    expect(critical, `Accessibility violations: ${JSON.stringify(critical, null, 2)}`).toHaveLength(0)
  })
})

// ── US-02: Candidate Profile Setup ───────────────────────────

test.describe('US-02 — Profile Setup', () => {
  test.beforeEach(async ({ page }) => { await registerAndLogin(page) })

  test('uploads a resume and sees parsed skills confirmed', async ({ page }) => {
    await page.goto(`${BASE_URL}/profile`)
    await page.getByLabel('Interview track').selectOption('software_engineering')
    await page.getByLabel('Career level').selectOption('mid')

    const fileInput = page.getByLabel('Upload resume')
    await fileInput.setInputFiles({
      name: 'test-resume.pdf',
      mimeType: 'application/pdf',
      buffer: Buffer.from('%PDF-1.4 test resume content'),
    })

    await expect(page.getByText(/we extracted/i)).toBeVisible({ timeout: 15_000 })
    await page.getByRole('button', { name: 'Confirm & Continue' }).click()
    await expect(page).toHaveURL(/\/dashboard/)
  })

  test('rejects files larger than 5MB', async ({ page }) => {
    await page.goto(`${BASE_URL}/profile`)
    const largeBuffer = Buffer.alloc(6 * 1024 * 1024, 'x')
    const fileInput = page.getByLabel('Upload resume')
    await fileInput.setInputFiles({ name: 'large.pdf', mimeType: 'application/pdf', buffer: largeBuffer })
    await expect(page.getByText(/file size exceeds/i)).toBeVisible()
  })
})

// ── US-03: Candidate Dashboard ────────────────────────────────

test.describe('US-03 — Candidate Dashboard', () => {
  test.beforeEach(async ({ page }) => { await registerAndLogin(page) })

  test('shows sessions completed, average score, and trend chart', async ({ page }) => {
    await page.goto(`${BASE_URL}/dashboard`)
    await expect(page.getByTestId('sessions-completed')).toBeVisible()
    await expect(page.getByTestId('average-score')).toBeVisible()
    await expect(page.getByTestId('score-trend-chart')).toBeVisible()
  })

  test('dashboard page has no critical accessibility violations', async ({ page }) => {
    await page.goto(`${BASE_URL}/dashboard`)
    const results = await new AxeBuilder({ page }).analyze()
    const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
    expect(critical).toHaveLength(0)
  })
})

// ── US-05: Browse & Filter Question Bank ─────────────────────

test.describe('US-05 — Question Bank Browse & Filter', () => {
  test.beforeEach(async ({ page }) => { await registerAndLogin(page) })

  test('displays paginated questions and applies type filter', async ({ page }) => {
    await page.goto(`${BASE_URL}/question-bank`)
    await expect(page.getByTestId('question-list')).toBeVisible()

    const initialCount = await page.locator('[data-testid="question-card"]').count()
    expect(initialCount).toBeGreaterThan(0)

    await page.getByLabel('Type').selectOption('behavioral')
    await expect(page.getByLabel('Type')).toHaveValue('behavioral')
    // Filter chip appears
    await expect(page.getByText('behavioral')).toBeVisible()

    const filteredCount = await page.locator('[data-testid="question-card"]').count()
    expect(filteredCount).toBeGreaterThan(0)
  })

  test('shows sample answer collapsed behind toggle', async ({ page }) => {
    await page.goto(`${BASE_URL}/question-bank`)
    await page.locator('[data-testid="question-card"]').first().click()
    await expect(page.getByRole('button', { name: /show answer/i })).toBeVisible()
    await page.getByRole('button', { name: /show answer/i }).click()
    await expect(page.getByTestId('sample-answer')).toBeVisible()
  })
})

// ── US-06: Search ─────────────────────────────────────────────

test.describe('US-06 — Search & Discovery', () => {
  test.beforeEach(async ({ page }) => { await registerAndLogin(page) })

  test('shows autocomplete suggestions after 2 characters', async ({ page }) => {
    await page.goto(`${BASE_URL}/question-bank`)
    const searchInput = page.getByRole('searchbox', { name: /search/i })
    await searchInput.fill('le')
    await expect(page.getByTestId('autocomplete-suggestions')).toBeVisible({ timeout: 2_000 })
    const suggestions = page.locator('[data-testid="autocomplete-suggestion"]')
    await expect(suggestions).toHaveCount({ minimum: 1 })
  })

  test('shows no-results state for unmatched query', async ({ page }) => {
    await page.goto(`${BASE_URL}/question-bank`)
    await page.getByRole('searchbox', { name: /search/i }).fill('xyznonexistentquery123')
    await expect(page.getByText(/no results/i)).toBeVisible({ timeout: 2_000 })
  })
})

// ── US-09: AI Mock Interview ──────────────────────────────────

test.describe('US-09 — AI Mock Interview Session', () => {
  test.use({
    // Grant camera/mic permissions for recording tests
    permissions: ['camera', 'microphone'],
  })

  test.beforeEach(async ({ page }) => { await registerAndLogin(page) })

  test('shows consent dialog before session starts', async ({ page }) => {
    await page.goto(`${BASE_URL}/mock-interview`)
    await page.getByRole('button', { name: /start ai mock/i }).click()
    await expect(page.getByRole('dialog', { name: /consent/i })).toBeVisible()
  })

  test('start session button is disabled until consent checkbox is checked', async ({ page }) => {
    await page.goto(`${BASE_URL}/mock-interview`)
    await page.getByRole('button', { name: /start ai mock/i }).click()

    const acceptButton = page.getByRole('button', { name: /accept.*start/i })
    await expect(acceptButton).toBeDisabled()

    await page.getByRole('checkbox', { name: /i have read/i }).check()
    await expect(acceptButton).toBeEnabled()
  })

  test('declining consent closes dialog and does not start session', async ({ page }) => {
    await page.goto(`${BASE_URL}/mock-interview`)
    await page.getByRole('button', { name: /start ai mock/i }).click()
    await page.getByRole('button', { name: /decline/i }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
    await expect(page).toHaveURL(/\/mock-interview/)
  })

  test('consent dialog has no critical accessibility violations', async ({ page }) => {
    await page.goto(`${BASE_URL}/mock-interview`)
    await page.getByRole('button', { name: /start ai mock/i }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    const results = await new AxeBuilder({ page }).analyze()
    const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
    expect(critical).toHaveLength(0)
  })
})

// ── US-15: Feedback Archive ───────────────────────────────────

test.describe('US-15 — Feedback Archive', () => {
  test.beforeEach(async ({ page }) => { await registerAndLogin(page) })

  test('lists sessions in reverse chronological order', async ({ page }) => {
    await page.goto(`${BASE_URL}/feedback`)
    const entries = page.locator('[data-testid="feedback-entry"]')
    const count = await entries.count()
    // Fresh account — no sessions yet
    if (count === 0) {
      await expect(page.getByText(/no sessions yet/i)).toBeVisible()
    } else {
      // Verify descending order by checking data-date attributes
      const dates = await entries.evaluateAll(
        (els) => els.map((el) => el.getAttribute('data-date') ?? ''),
      )
      const sorted = [...dates].sort((a, b) => b.localeCompare(a))
      expect(dates).toEqual(sorted)
    }
  })

  test('feedback archive page has no critical accessibility violations', async ({ page }) => {
    await page.goto(`${BASE_URL}/feedback`)
    const results = await new AxeBuilder({ page }).analyze()
    const critical = results.violations.filter(v => v.impact === 'critical' || v.impact === 'serious')
    expect(critical).toHaveLength(0)
  })
})
