-- Migration: 002_seed_questions
-- Description: Seed initial question bank (50 questions — 25 Behavioral, 25 Technical)
-- Generated by: db_developer_agent | Date: 2026-05-26

BEGIN;

-- Insert a system admin user for content attribution
INSERT INTO users (id, email_hash, email_encrypted, full_name_encrypted, role, status, email_verified)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'system',
  'system'::bytea,
  'system'::bytea,
  'admin',
  'active',
  TRUE
) ON CONFLICT DO NOTHING;

-- ─── Behavioral Questions ─────────────────────────────────────

INSERT INTO questions (type, industry, career_level, difficulty, text, framework, tags, status, created_by, published_at) VALUES
('behavioral', 'general', 'entry',  2, 'Tell me about a time you had to learn something new quickly. How did you approach it?',                         'STAR', ARRAY['learning','adaptability'],           'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'entry',  2, 'Describe a situation where you worked as part of a team to achieve a goal.',                                    'STAR', ARRAY['teamwork','collaboration'],           'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'mid',    3, 'Tell me about a time you disagreed with a decision made by your manager. How did you handle it?',               'STAR', ARRAY['conflict','communication','leadership'],'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'mid',    3, 'Describe a situation where you had to manage multiple competing priorities. What did you do?',                   'STAR', ARRAY['prioritization','time-management'],   'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'mid',    3, 'Tell me about a time you failed at something. What did you learn from it?',                                      'STAR', ARRAY['resilience','growth-mindset'],         'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'senior', 4, 'Describe a time you led a team through significant change or uncertainty.',                                       'STAR', ARRAY['leadership','change-management'],     'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'senior', 4, 'Tell me about a time you had to influence stakeholders without direct authority.',                               'STAR', ARRAY['influence','stakeholder-management'],  'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'senior', 4, 'Describe the most complex problem you have solved. Walk me through your approach.',                               'STAR', ARRAY['problem-solving','analytical'],        'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'mid',    3, 'Give me an example of a time you showed initiative beyond your job description.',                                 'STAR', ARRAY['initiative','ownership'],              'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'entry',  2, 'Tell me about a time you received critical feedback. How did you respond?',                                       'STAR', ARRAY['feedback','growth'],                   'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'mid',    3, 'Describe a time when you had to deliver difficult news to a colleague or client.',                                'STAR', ARRAY['communication','empathy'],             'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'senior', 4, 'Tell me about a strategic decision you made that had a significant long-term impact.',                            'STAR', ARRAY['strategy','decision-making'],          'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'entry',  2, 'Describe a goal you set for yourself and how you achieved it.',                                                   'STAR', ARRAY['goal-setting','motivation'],           'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'mid',    3, 'Tell me about a time you had to work with a difficult team member. How did you handle it?',                      'STAR', ARRAY['conflict-resolution','teamwork'],      'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'general', 'senior', 5, 'Describe how you built and scaled a high-performing team from scratch.',                                          'STAR', ARRAY['leadership','hiring','culture'],       'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'software_engineering', 'mid',    3, 'Tell me about a time a production incident occurred on your watch. How did you respond?',           'STAR', ARRAY['incident-response','accountability'],  'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'software_engineering', 'senior', 4, 'Describe a time you had to push back on a feature request due to technical constraints.',           'STAR', ARRAY['technical-leadership','communication'],'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'software_engineering', 'mid',    3, 'Tell me about a time you improved the performance of a system significantly.',                       'STAR', ARRAY['performance','optimization'],          'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'software_engineering', 'entry',  2, 'Describe a time you had to debug a particularly challenging problem.',                               'STAR', ARRAY['debugging','problem-solving'],         'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'software_engineering', 'senior', 4, 'Tell me about a major technical decision you owned end-to-end. What was the outcome?',              'STAR', ARRAY['architecture','ownership'],            'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'medical_residency',    'entry',  2, 'Tell me about a time you made an error in a clinical setting. How did you handle it?',               'STAR', ARRAY['patient-safety','accountability'],     'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'medical_residency',    'mid',    3, 'Describe a challenging patient case and how you collaborated with the care team.',                   'STAR', ARRAY['teamwork','clinical','communication'], 'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'medical_residency',    'entry',  2, 'Tell me why you chose this specialty and what you hope to contribute to the field.',                 'STAR', ARRAY['motivation','specialty-fit'],          'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'medical_residency',    'mid',    3, 'Describe a time you had to deliver bad news to a patient or family. How did you approach it?',       'STAR', ARRAY['communication','empathy','clinical'],  'published', '00000000-0000-0000-0000-000000000001', NOW()),
('behavioral', 'medical_residency',    'senior', 4, 'Tell me about a time you advocated for a patient against institutional or systemic barriers.',       'STAR', ARRAY['advocacy','ethics','leadership'],      'published', '00000000-0000-0000-0000-000000000001', NOW());

-- ─── Technical Questions ──────────────────────────────────────

INSERT INTO questions (type, industry, career_level, difficulty, text, framework, tags, status, created_by, published_at) VALUES
('technical', 'software_engineering', 'entry',  2, 'Explain the difference between a process and a thread.',                                             NULL, ARRAY['os','concurrency'],                   'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'entry',  2, 'What is the time complexity of binary search and why?',                                               NULL, ARRAY['algorithms','complexity'],            'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'entry',  2, 'Explain REST vs GraphQL. When would you choose one over the other?',                                  NULL, ARRAY['api','web'],                          'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'How would you design a URL shortener like bit.ly? Walk me through the system design.',                NULL, ARRAY['system-design','databases','scale'],  'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'Explain ACID properties in databases. Give an example of when each matters.',                         NULL, ARRAY['databases','transactions'],           'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'How does indexing work in a relational database? What are the trade-offs?',                           NULL, ARRAY['databases','performance'],            'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    4, 'Design a rate limiter. What algorithms would you consider and what are the trade-offs?',               NULL, ARRAY['system-design','algorithms'],         'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'senior', 4, 'How would you design a real-time notification system for 10 million users?',                          NULL, ARRAY['system-design','scale','websockets'],  'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'senior', 5, 'Describe how you would migrate a monolith to microservices without downtime.',                        NULL, ARRAY['architecture','microservices'],        'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'senior', 5, 'How would you design a distributed caching layer? What are the consistency trade-offs?',              NULL, ARRAY['system-design','caching','distributed'],'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'entry',  2, 'What is the difference between SQL JOIN types (INNER, LEFT, RIGHT, FULL)?',                           NULL, ARRAY['sql','databases'],                    'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'Explain how React renders and re-renders. What triggers a re-render?',                                NULL, ARRAY['react','frontend','performance'],     'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'How does JWT authentication work? What are the security considerations?',                              NULL, ARRAY['security','auth','jwt'],              'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'senior', 4, 'How would you approach building a CI/CD pipeline for a team of 50 engineers?',                        NULL, ARRAY['devops','cicd','process'],            'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'entry',  2, 'What is the difference between synchronous and asynchronous programming?',                             NULL, ARRAY['async','fundamentals'],               'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'Explain the CAP theorem. How does it affect your choice of database?',                                NULL, ARRAY['distributed-systems','databases'],    'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'senior', 4, 'How would you design the data model for a multi-tenant SaaS application?',                            NULL, ARRAY['databases','saas','architecture'],    'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'What are the SOLID principles? Give an example of each in code.',                                     NULL, ARRAY['oop','design-principles'],            'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'entry',  2, 'Explain how HTTPS works. What happens during the TLS handshake?',                                    NULL, ARRAY['networking','security'],              'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'senior', 5, 'How would you architect a payment processing system? What are the key reliability concerns?',         NULL, ARRAY['system-design','payments','reliability'],'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'What is N+1 query problem and how do you fix it?',                                                    NULL, ARRAY['performance','databases','orm'],      'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'entry',  2, 'Explain the event loop in Node.js.',                                                                  NULL, ARRAY['nodejs','async','fundamentals'],      'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'senior', 4, 'How would you implement feature flags in a large production system?',                                 NULL, ARRAY['architecture','feature-flags','devops'],'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'What are the different types of testing (unit, integration, E2E)? When do you use each?',             NULL, ARRAY['testing','quality'],                  'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'senior', 4, 'How would you design an API versioning strategy for a public API with millions of consumers?',        NULL, ARRAY['api','versioning','backward-compat'],  'published', '00000000-0000-0000-0000-000000000001', NOW()),
('technical', 'software_engineering', 'mid',    3, 'Explain how you would implement optimistic UI updates and handle rollback on failure.',                NULL, ARRAY['frontend','ux','error-handling'],     'published', '00000000-0000-0000-0000-000000000001', NOW());

-- ─── Sample Answers (select questions) ───────────────────────

INSERT INTO question_answers (question_id, answer_text, keywords, is_primary, created_by)
SELECT id,
  'A strong answer uses the STAR method: Situation (briefly set the context), Task (your specific responsibility), Action (what YOU did — use "I" not "we"), Result (quantify the outcome where possible). Example: "In my previous role as a junior engineer, we had a major deployment blocked by a flaky integration test I had never seen before (S). My task was to unblock the team within the afternoon (T). I isolated the test, traced it to a race condition in our async fixture setup, and wrote a deterministic mock (A). This fixed the deployment and I added the fix to our onboarding docs, preventing it for future engineers (R)."',
  ARRAY['STAR','situation','task','action','result','specific','quantify'],
  TRUE,
  '00000000-0000-0000-0000-000000000001'
FROM questions
WHERE text LIKE 'Tell me about a time you had to learn something new%'
  AND type = 'behavioral'
LIMIT 1;

INSERT INTO question_answers (question_id, answer_text, keywords, is_primary, created_by)
SELECT id,
  'For a URL shortener: 1) Generate a short key (6-char base62 = 56bn combinations). 2) Hash the long URL (MD5/SHA) and store in a key-value store (Redis for hot paths, PostgreSQL for persistence). 3) Use a 301 redirect (or 302 if you need click analytics). Scale considerations: separate read and write paths; reads are 100:1 vs writes. Use CDN for popular URLs. Handle collisions with retry or counter-based generation. Mention: custom aliases, expiry TTLs, analytics pipeline (Kafka → ClickHouse). Design for 100M URLs/day = ~1157 QPS writes.',
  ARRAY['base62','key-value','Redis','CDN','301 redirect','hash','scale','QPS','analytics'],
  TRUE,
  '00000000-0000-0000-0000-000000000001'
FROM questions
WHERE text LIKE 'How would you design a URL shortener%'
  AND type = 'technical'
LIMIT 1;

COMMIT;
