/**
 * Unit tests — auth.service.ts
 * Generated by: qa_developer_agent | Date: 2026-05-26
 */

import { describe, it, expect, vi, beforeEach } from 'vitest'

vi.mock('@/db/connection', () => ({ db: { select: vi.fn(), insert: vi.fn(), update: vi.fn() } }))
vi.mock('@/modules/notification/email.service', () => ({
  emailService: { sendVerificationEmail: vi.fn().mockResolvedValue(undefined) },
}))
vi.mock('@/modules/admin/audit.service', () => ({
  auditLog: { record: vi.fn().mockResolvedValue(undefined) },
}))

import { authService } from '@/modules/auth/auth.service'
import { db } from '@/db/connection'
import { emailService } from '@/modules/notification/email.service'
import bcrypt from 'bcrypt'

const mockDb = db as {
  select: ReturnType<typeof vi.fn>
  insert: ReturnType<typeof vi.fn>
  update: ReturnType<typeof vi.fn>
}

function mockSelectReturning(rows: unknown[]) {
  mockDb.select.mockReturnValue({
    from: vi.fn().mockReturnValue({
      where: vi.fn().mockReturnValue({
        limit: vi.fn().mockResolvedValue(rows),
      }),
    }),
  })
}

function mockInsertReturning(rows: unknown[]) {
  mockDb.insert.mockReturnValue({
    values: vi.fn().mockReturnValue({
      returning: vi.fn().mockResolvedValue(rows),
    }),
  })
}

// ── Registration ───────────────────────────────────────────────

describe('authService.register', () => {
  beforeEach(() => vi.clearAllMocks())

  it('creates a new candidate account and sends verification email', async () => {
    mockSelectReturning([]) // no existing user
    mockInsertReturning([{ id: 'usr-001', role: 'candidate' }])

    const result = await authService.register({
      email: 'jane@example.com',
      password: 'SecurePass1!',
      full_name: 'Jane Smith',
      role: 'candidate',
    })

    expect(result.user_id).toBe('usr-001')
    expect(result.role).toBe('candidate')
    expect(emailService.sendVerificationEmail).toHaveBeenCalledOnce()
    expect(emailService.sendVerificationEmail).toHaveBeenCalledWith(
      'jane@example.com',
      expect.any(String),
    )
  })

  it('throws EMAIL_EXISTS when email is already registered', async () => {
    mockSelectReturning([{ id: 'usr-existing' }])

    await expect(
      authService.register({
        email: 'existing@example.com',
        password: 'SecurePass1!',
        full_name: 'Existing User',
        role: 'candidate',
      }),
    ).rejects.toMatchObject({ code: 'EMAIL_EXISTS', status: 409 })

    expect(mockDb.insert).not.toHaveBeenCalled()
    expect(emailService.sendVerificationEmail).not.toHaveBeenCalled()
  })

  it('hashes the password before storing (never stores plaintext)', async () => {
    mockSelectReturning([])
    let storedValues: Record<string, unknown> = {}

    mockDb.insert.mockReturnValue({
      values: vi.fn().mockImplementation((values) => {
        storedValues = values
        return { returning: vi.fn().mockResolvedValue([{ id: 'usr-002', role: 'candidate' }]) }
      }),
    })

    await authService.register({
      email: 'new@example.com',
      password: 'MyPlainPassword!',
      full_name: 'New User',
      role: 'candidate',
    })

    expect(storedValues.passwordHash).toBeDefined()
    expect(storedValues.passwordHash).not.toBe('MyPlainPassword!')
    const isHashed = await bcrypt.compare('MyPlainPassword!', storedValues.passwordHash as string)
    expect(isHashed).toBe(true)
  })
})

// ── Login ──────────────────────────────────────────────────────

describe('authService.login', () => {
  const passwordHash = bcrypt.hashSync('CorrectPass1!', 12)

  beforeEach(() => vi.clearAllMocks())

  it('returns access and refresh tokens on valid credentials', async () => {
    mockSelectReturning([{
      id: 'usr-001',
      role: 'candidate',
      status: 'active',
      emailVerified: true,
      passwordHash,
    }])

    const result = await authService.login(
      { email: 'jane@example.com', password: 'CorrectPass1!' },
      '127.0.0.1',
    )

    expect(result.access_token).toBeDefined()
    expect(result.refresh_token).toBeDefined()
    expect(result.expires_in).toBe(900)
  })

  it('throws INVALID_CREDENTIALS for wrong password', async () => {
    mockSelectReturning([{
      id: 'usr-001',
      role: 'candidate',
      status: 'active',
      emailVerified: true,
      passwordHash,
    }])

    await expect(
      authService.login(
        { email: 'jane@example.com', password: 'WrongPassword!' },
        '127.0.0.1',
      ),
    ).rejects.toMatchObject({ code: 'INVALID_CREDENTIALS', status: 401 })
  })

  it('throws INVALID_CREDENTIALS when user does not exist (timing-safe)', async () => {
    mockSelectReturning([]) // user not found

    const start = Date.now()
    await expect(
      authService.login(
        { email: 'ghost@example.com', password: 'AnyPass1!' },
        '127.0.0.1',
      ),
    ).rejects.toMatchObject({ code: 'INVALID_CREDENTIALS' })

    // bcrypt.compare runs even for non-existent users (timing attack prevention)
    // Should take at least 50ms (bcrypt with factor 12)
    expect(Date.now() - start).toBeGreaterThan(50)
  })

  it('throws ACCOUNT_SUSPENDED for suspended accounts', async () => {
    mockSelectReturning([{
      id: 'usr-suspended',
      role: 'candidate',
      status: 'suspended',
      emailVerified: true,
      passwordHash,
    }])

    await expect(
      authService.login(
        { email: 'suspended@example.com', password: 'CorrectPass1!' },
        '127.0.0.1',
      ),
    ).rejects.toMatchObject({ code: 'ACCOUNT_SUSPENDED', status: 403 })
  })

  it('throws EMAIL_NOT_VERIFIED for unverified accounts', async () => {
    mockSelectReturning([{
      id: 'usr-unverified',
      role: 'candidate',
      status: 'active',
      emailVerified: false,
      passwordHash,
    }])

    await expect(
      authService.login(
        { email: 'unverified@example.com', password: 'CorrectPass1!' },
        '127.0.0.1',
      ),
    ).rejects.toMatchObject({ code: 'EMAIL_NOT_VERIFIED', status: 403 })
  })
})

// ── Email Verification ────────────────────────────────────────

describe('authService.verifyEmail', () => {
  beforeEach(() => vi.clearAllMocks())

  it('verifies email with valid, non-expired token', async () => {
    mockSelectReturning([{
      id: 'usr-001',
      expiry: new Date(Date.now() + 3600_000), // 1 hour from now
    }])

    mockDb.update.mockReturnValue({
      set: vi.fn().mockReturnValue({
        where: vi.fn().mockResolvedValue(undefined),
      }),
    })

    const result = await authService.verifyEmail('valid-token-abc')
    expect(result.verified).toBe(true)
  })

  it('throws INVALID_TOKEN for expired token', async () => {
    mockSelectReturning([{
      id: 'usr-001',
      expiry: new Date(Date.now() - 1000), // expired 1 second ago
    }])

    await expect(authService.verifyEmail('expired-token')).rejects.toMatchObject({
      code: 'INVALID_TOKEN',
      status: 400,
    })
  })

  it('throws INVALID_TOKEN when token does not exist', async () => {
    mockSelectReturning([]) // no user found

    await expect(authService.verifyEmail('unknown-token')).rejects.toMatchObject({
      code: 'INVALID_TOKEN',
      status: 400,
    })
  })
})
