/**
 * Unit tests — scoring.service.ts
 * Generated by: qa_developer_agent | Date: 2026-05-26
 *
 * Mocking strategy:
 *   - DB (Drizzle): mocked — deterministic queries
 *   - Anthropic Claude API: mocked — avoid real API calls in unit tests
 *   - logger / metrics: mocked — prevent stdout noise
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'

// ── Mock external dependencies before importing the module ─────
vi.mock('@anthropic-ai/sdk', () => ({
  default: vi.fn().mockImplementation(() => ({
    messages: {
      create: vi.fn().mockResolvedValue({
        content: [
          {
            type: 'text',
            text: JSON.stringify({
              keyword_relevance: 78,
              improvement_tip: 'Include more specific metrics in your answer.',
            }),
          },
        ],
      }),
    },
  })),
}))

vi.mock('@/db/connection', () => ({ db: { select: vi.fn(), update: vi.fn() } }))
vi.mock('@/lib/logger', () => ({ logger: { info: vi.fn(), warn: vi.fn(), error: vi.fn() } }))
vi.mock('@/lib/metrics', () => ({ metrics: { scoreReportLatency: vi.fn() } }))

// ── Import after mocks ─────────────────────────────────────────
import { scoringService } from '@/modules/scoring/scoring.service'
import { db } from '@/db/connection'
import Anthropic from '@anthropic-ai/sdk'

// ── Test helpers ───────────────────────────────────────────────

function makeResponse(overrides = {}) {
  return {
    id: 'res-001',
    sessionId: 'sess-001',
    questionId: 'q-001',
    responseIndex: 0,
    transcript: 'I led a team of five engineers through a migration to microservices. We identified dependencies, ran parallel services, and rolled out incrementally.',
    durationSeconds: 45,
    ...overrides,
  }
}

function makeSession(overrides = {}) {
  return {
    id: 'sess-001',
    candidateId: 'user-001',
    status: 'processing',
    ...overrides,
  }
}

// ── Tests ──────────────────────────────────────────────────────

describe('scoringService.scoreSession', () => {
  beforeEach(() => {
    vi.clearAllMocks()

    // Default DB mock chain
    const mockDb = db as unknown as { select: ReturnType<typeof vi.fn>; update: ReturnType<typeof vi.fn> }

    mockDb.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockReturnValue({
          orderBy: vi.fn().mockResolvedValue([makeResponse()]),
        }),
      }),
    })

    mockDb.update.mockReturnValue({
      set: vi.fn().mockReturnValue({
        where: vi.fn().mockResolvedValue(undefined),
      }),
    })
  })

  it('scores a session with a single response and writes composite to DB', async () => {
    await scoringService.scoreSession('sess-001')

    expect(db.update).toHaveBeenCalledTimes(2) // once for response, once for session
  })

  it('handles a session with no transcript gracefully (skips response)', async () => {
    const mockDb = db as unknown as { select: ReturnType<typeof vi.fn>; update: ReturnType<typeof vi.fn> }
    mockDb.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockReturnValue({
          orderBy: vi.fn().mockResolvedValue([makeResponse({ transcript: null })]),
        }),
      }),
    })

    await expect(scoringService.scoreSession('sess-001')).resolves.not.toThrow()
    // Session update still runs to mark status = scored with 0 composite
    expect(db.update).toHaveBeenCalledTimes(1)
  })

  it('falls back to local tip when Claude API throws', async () => {
    const anthropicInstance = (Anthropic as unknown as ReturnType<typeof vi.fn>).mock.results[0].value
    anthropicInstance.messages.create.mockRejectedValueOnce(new Error('Rate limited'))

    await expect(scoringService.scoreSession('sess-001')).resolves.not.toThrow()
    // Should still update DB — scoring with fallback values
    expect(db.update).toHaveBeenCalled()
  })
})

describe('filler word detection', () => {
  // Access private function through scoring pipeline by testing observable output

  it('detects common filler words in transcript', async () => {
    const mockDb = db as unknown as { select: ReturnType<typeof vi.fn>; update: ReturnType<typeof vi.fn> }
    let capturedSet: Record<string, unknown> = {}

    mockDb.update.mockReturnValue({
      set: vi.fn().mockImplementation((values) => {
        capturedSet = values
        return { where: vi.fn().mockResolvedValue(undefined) }
      }),
    })

    mockDb.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockReturnValue({
          orderBy: vi.fn().mockResolvedValue([
            makeResponse({
              transcript: 'Um so basically I think like you know I led the team',
              durationSeconds: 10,
            }),
          ]),
        }),
      }),
    })

    await scoringService.scoreSession('sess-001')

    const responseUpdate = mockDb.update.mock.calls[0]
    expect(responseUpdate).toBeDefined()
    // capturedSet should have filler_word_count > 0
    expect((capturedSet as { fillerWordCount?: number }).fillerWordCount).toBeGreaterThan(0)
  })

  it('reports zero filler words for clean transcript', async () => {
    const mockDb = db as unknown as { select: ReturnType<typeof vi.fn>; update: ReturnType<typeof vi.fn> }
    let capturedSet: Record<string, unknown> = {}

    mockDb.update.mockReturnValue({
      set: vi.fn().mockImplementation((values) => {
        capturedSet = values
        return { where: vi.fn().mockResolvedValue(undefined) }
      }),
    })

    mockDb.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockReturnValue({
          orderBy: vi.fn().mockResolvedValue([
            makeResponse({
              transcript: 'I led a cross-functional team through a complex migration project.',
              durationSeconds: 10,
            }),
          ]),
        }),
      }),
    })

    await scoringService.scoreSession('sess-001')

    expect((capturedSet as { fillerWordCount?: number }).fillerWordCount).toBe(0)
  })
})

describe('speech rate calculation', () => {
  it('calculates WPM correctly from word count and duration', async () => {
    // 30 words in 15 seconds = 120 WPM
    const transcript = 'word '.repeat(30).trim()
    const mockDb = db as unknown as { select: ReturnType<typeof vi.fn>; update: ReturnType<typeof vi.fn> }
    let capturedSet: Record<string, unknown> = {}

    mockDb.update.mockReturnValue({
      set: vi.fn().mockImplementation((values) => {
        capturedSet = values
        return { where: vi.fn().mockResolvedValue(undefined) }
      }),
    })

    mockDb.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockReturnValue({
          orderBy: vi.fn().mockResolvedValue([
            makeResponse({ transcript, durationSeconds: 15 }),
          ]),
        }),
      }),
    })

    await scoringService.scoreSession('sess-001')

    expect((capturedSet as { speechRateWpm?: number }).speechRateWpm).toBe(120)
  })

  it('returns 0 WPM when duration is 0', async () => {
    const mockDb = db as unknown as { select: ReturnType<typeof vi.fn>; update: ReturnType<typeof vi.fn> }
    let capturedSet: Record<string, unknown> = {}

    mockDb.update.mockReturnValue({
      set: vi.fn().mockImplementation((values) => {
        capturedSet = values
        return { where: vi.fn().mockResolvedValue(undefined) }
      }),
    })

    mockDb.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockReturnValue({
          orderBy: vi.fn().mockResolvedValue([
            makeResponse({ durationSeconds: 0 }),
          ]),
        }),
      }),
    })

    await scoringService.scoreSession('sess-001')

    expect((capturedSet as { speechRateWpm?: number }).speechRateWpm).toBe(0)
  })
})

describe('clarity score computation', () => {
  it('produces score between 0 and 100', async () => {
    const mockDb = db as unknown as { select: ReturnType<typeof vi.fn>; update: ReturnType<typeof vi.fn> }

    // Collect session update values (second update call)
    const sessionUpdateSets: unknown[] = []
    mockDb.update.mockReturnValue({
      set: vi.fn().mockImplementation((values) => {
        sessionUpdateSets.push(values)
        return { where: vi.fn().mockResolvedValue(undefined) }
      }),
    })

    mockDb.select.mockReturnValue({
      from: vi.fn().mockReturnValue({
        where: vi.fn().mockReturnValue({
          orderBy: vi.fn().mockResolvedValue([makeResponse()]),
        }),
      }),
    })

    await scoringService.scoreSession('sess-001')

    const sessionUpdate = sessionUpdateSets[sessionUpdateSets.length - 1] as { compositeScore?: number }
    expect(sessionUpdate?.compositeScore).toBeGreaterThanOrEqual(0)
    expect(sessionUpdate?.compositeScore).toBeLessThanOrEqual(100)
  })
})
